version : "3.6"
services:
  chrome_test:
    hostname: chrome_tests
    build:
      context: ../
      dockerfile: .docker/run_chrome_tests
    volumes:
    - ./target:/usr/repo/target
      - 'maven_repo:/root/.m2'
volumes:
  maven_repo:
    driver: local

networks:
  web_tests:
    name: web_tests
    external: true

